### ISSUE TITLE
지금까지 만든거 다 정리해서 올렸습니다.

### ISSUE THREAD

**Issue by dnfwlxo11** [OpenScourcelecture/OpenSource_A-Team-final#1]
지금까지 만든거 다 정리해서 올렸습니다.

휘훈씨는 ppt올린거 확인하고 발표 준비해주세요~~

실행파일로 exe 만들자고 했었는데 오늘까지 해봐도 안되서

그냥 패스하기로 했습니다.

**Comment by helloworld11223** [comment]
넵 그런데 피피티내용에 깃허브 내용도 추가하면 좋을거같은데 지금되나여

**Comment by dnfwlxo11** [comment]
추가할까말까 했는데 그냥 ppt 목표에 깃허브 협업내용있는데 그거 설명하면서 깃허브 팀게시판, 저장소 이슈란으로 중요 공지했다고  설명하시면 될거같아요

**Comment by helloworld11223** [comment]
아 늦은시간에 감사합니다
